[workspace]
resolver = "2"
members = [
  "./key-import-common",
  "./key-import-client",
  "./key-export-common",
  "./key-export-client",
  "./core",
]

[patch.crates-io.key-share]
git = "https://github.com/dfns/cggmp21"
branch = "zero-sk"
