[package]
name = "dfns-key-import"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
serde_json = "1"

dfns-key-import-common = { path = "../key-import-common" }