[package]
name = "dfns-key-export-client"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
serde_json = "1"
rand_core = { version = "0.6", default-features = false }

generic-ec = { git = "https://github.com/dfns-labs/generic-ec", branch = "m", default-features = false, features = ["serde", "curve-secp256k1", "wasm"] }
generic-ec-zkp = { git = "https://github.com/dfns-labs/generic-ec", branch = "m", default-features = false, features = ["serde", "alloc"] }

# We are using the encryption scheme defined in key-import repo:
dfns-key-import-common = { git = "https://github.com/dfns-labs/trusted-dealer", branch = "m" }

dfns-key-export-common = { path = "../key-export-common" }

[dev-dependencies]
hex = { version = "0.4", default-features = false, features = ["alloc", "serde"]}