name: Rust

on:
  pull_request:
    branches: [ "*" ]
  schedule:
    - cron: '0 5 * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - dfns-trusted-dealer-common
          - dfns-key-import
          - dfns-key-export
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Run tests
      run: cargo check -p ${{ matrix.package }}
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Run tests
      run: cargo test
  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt --all -- --check
  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Run clippy
      run: cargo clippy --all --lib -- -D clippy::all -D clippy::unwrap_used -D clippy::expect_used
    - name: Run clippy tests
      run: cargo clippy --tests -- -D clippy::all
  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Install wasm32-unknown-unknown toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Build import client on wasm32-unknown-unknown
      run:
        cargo check -p dfns-key-import --target wasm32-unknown-unknown
    - name: Build export client on wasm32-unknown-unknown
      run:
        cargo check -p dfns-key-export --target wasm32-unknown-unknown
    - name: Install wasm-pack
      uses: baptiste0928/cargo-install@v1
      with:
        crate: wasm-pack
    - name: wasm-pack an example project for import client
      run: (cd key-import; wasm-pack build)
    - name: wasm-pack an example project for export client
      run: (cd key-export; wasm-pack build)
